// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderTrak.API.Models.OrderTrakDB;

#nullable disable

namespace OrderTrak.API.Migrations
{
    [DbContext(typeof(OrderTrakContext))]
    [Migration("20250425185602_Order_OrderLines")]
    partial class Order_OrderLines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.INV_Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("INV_Receipt");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.INV_Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("POLineID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptID")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<int>("StockGroupID")
                        .HasColumnType("int");

                    b.Property<string>("UDF1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LocationID");

                    b.HasIndex("POLineID");

                    b.HasIndex("ReceiptID");

                    b.HasIndex("StatusID");

                    b.HasIndex("StockGroupID");

                    b.ToTable("INV_Stock");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.INV_StockStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("StockStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("INV_StockStatus");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.ORD_Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("POLineID")
                        .HasColumnType("int");

                    b.Property<int>("PartID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockGroupID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrderID");

                    b.HasIndex("POLineID");

                    b.HasIndex("PartID");

                    b.HasIndex("StockGroupID");

                    b.ToTable("ORD_Line");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.ORD_Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualShipDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("OrderUDF1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderUDF10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderUDF2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderUDF3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderUDF4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderUDF5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderUDF6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderUDF7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderUDF8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderUDF9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RequestedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequestedShipDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StakeHolderEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ORD_Order");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.PO_Header", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("PONumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectID");

                    b.ToTable("PO_Header");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.PO_Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSerialized")
                        .HasColumnType("bit");

                    b.Property<int>("POHeaderID")
                        .HasColumnType("int");

                    b.Property<int>("PartID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("POHeaderID");

                    b.HasIndex("PartID");

                    b.ToTable("PO_Line");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.SYS_ChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SYS_ChangeLog");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.SYS_ChangeLogDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChangeLogId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("TicketID")
                        .HasColumnType("int");

                    b.Property<string>("TicketInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChangeLogId");

                    b.ToTable("SYS_ChangeLogDetails");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.SYS_Function", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SYS_Function");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.SYS_Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SYS_Roles");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.SYS_RolesToFunction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanAccess")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FunctionID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FunctionID");

                    b.HasIndex("RoleID");

                    b.ToTable("SYS_RolesToFunction");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.SYS_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleID");

                    b.ToTable("SYS_Users");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.UPL_Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UPL_Customer");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.UPL_Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Depth")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Height")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LocationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UOMID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Width")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("UOMID");

                    b.ToTable("UPL_Location");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.UPL_PartInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Depth")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Height")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStock")
                        .HasColumnType("bit");

                    b.Property<decimal>("PartCost")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("PartDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartVendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UOMID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Width")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("UOMID");

                    b.ToTable("UPL_PartInfo");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.UPL_Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("OrderUDF1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderUDF10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderUDF2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderUDF3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderUDF4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderUDF5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderUDF6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderUDF7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderUDF8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderUDF9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StakeHolderEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDF9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID");

                    b.ToTable("UPL_Project");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.UPL_StockGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("StockGroupTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UPL_StockGroup");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.UPL_UOM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FormID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UnitOfMeasurement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UPL_UOM");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.INV_Stock", b =>
                {
                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.UPL_Location", "UPL_Location")
                        .WithMany("INV_Stock")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.PO_Line", "PO_Line")
                        .WithMany("INV_Stock")
                        .HasForeignKey("POLineID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.INV_Receipt", "INV_Receipt")
                        .WithMany("INV_Stock")
                        .HasForeignKey("ReceiptID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.INV_StockStatus", "INV_StockStatus")
                        .WithMany("INV_Stock")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.UPL_StockGroup", "UPL_StockGroup")
                        .WithMany("INV_Stock")
                        .HasForeignKey("StockGroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("INV_Receipt");

                    b.Navigation("INV_StockStatus");

                    b.Navigation("PO_Line");

                    b.Navigation("UPL_Location");

                    b.Navigation("UPL_StockGroup");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.ORD_Line", b =>
                {
                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.ORD_Order", "ORD_Order")
                        .WithMany("ORD_Line")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.PO_Line", "PO_Line")
                        .WithMany("ORD_Line")
                        .HasForeignKey("POLineID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.UPL_PartInfo", "UPL_PartInfo")
                        .WithMany("ORD_Line")
                        .HasForeignKey("PartID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.UPL_StockGroup", "UPL_StockGroup")
                        .WithMany("ORD_Line")
                        .HasForeignKey("StockGroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ORD_Order");

                    b.Navigation("PO_Line");

                    b.Navigation("UPL_PartInfo");

                    b.Navigation("UPL_StockGroup");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.PO_Header", b =>
                {
                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.UPL_Project", "UPL_Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UPL_Project");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.PO_Line", b =>
                {
                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.PO_Header", "PO_Header")
                        .WithMany("PO_Line")
                        .HasForeignKey("POHeaderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.UPL_PartInfo", "UPL_PartInfo")
                        .WithMany("PO_Line")
                        .HasForeignKey("PartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PO_Header");

                    b.Navigation("UPL_PartInfo");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.SYS_ChangeLogDetails", b =>
                {
                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.SYS_ChangeLog", "SYS_ChangeLog")
                        .WithMany("SYS_ChangeLogDetails")
                        .HasForeignKey("ChangeLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SYS_ChangeLog");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.SYS_RolesToFunction", b =>
                {
                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.SYS_Function", "SYS_Function")
                        .WithMany("SYS_RolesToFunction")
                        .HasForeignKey("FunctionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.SYS_Roles", "SYS_Roles")
                        .WithMany("SYS_RolesToFunction")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SYS_Function");

                    b.Navigation("SYS_Roles");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.SYS_User", b =>
                {
                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.SYS_Roles", "SYS_Roles")
                        .WithMany("SYS_User")
                        .HasForeignKey("RoleID");

                    b.Navigation("SYS_Roles");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.UPL_Location", b =>
                {
                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.UPL_UOM", "UPL_UOM")
                        .WithMany("UPL_Location")
                        .HasForeignKey("UOMID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UPL_UOM");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.UPL_PartInfo", b =>
                {
                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.UPL_UOM", "UPL_UOM")
                        .WithMany("UPL_PartInfo")
                        .HasForeignKey("UOMID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UPL_UOM");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.UPL_Project", b =>
                {
                    b.HasOne("OrderTrak.API.Models.OrderTrakDB.UPL_Customer", "UPL_Customer")
                        .WithMany("UPL_Projects")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UPL_Customer");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.INV_Receipt", b =>
                {
                    b.Navigation("INV_Stock");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.INV_StockStatus", b =>
                {
                    b.Navigation("INV_Stock");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.ORD_Order", b =>
                {
                    b.Navigation("ORD_Line");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.PO_Header", b =>
                {
                    b.Navigation("PO_Line");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.PO_Line", b =>
                {
                    b.Navigation("INV_Stock");

                    b.Navigation("ORD_Line");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.SYS_ChangeLog", b =>
                {
                    b.Navigation("SYS_ChangeLogDetails");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.SYS_Function", b =>
                {
                    b.Navigation("SYS_RolesToFunction");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.SYS_Roles", b =>
                {
                    b.Navigation("SYS_RolesToFunction");

                    b.Navigation("SYS_User");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.UPL_Customer", b =>
                {
                    b.Navigation("UPL_Projects");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.UPL_Location", b =>
                {
                    b.Navigation("INV_Stock");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.UPL_PartInfo", b =>
                {
                    b.Navigation("ORD_Line");

                    b.Navigation("PO_Line");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.UPL_StockGroup", b =>
                {
                    b.Navigation("INV_Stock");

                    b.Navigation("ORD_Line");
                });

            modelBuilder.Entity("OrderTrak.API.Models.OrderTrakDB.UPL_UOM", b =>
                {
                    b.Navigation("UPL_Location");

                    b.Navigation("UPL_PartInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
